///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
import 'package:i18n_tr/i18n_config.dart';
import '_source_text.dart';
import 'zh_cn.dart';
import 'en_us.dart';
import 'ja_jp.dart';

const I18nRuntimeConfig i18nConfig = I18nRuntimeConfig(
  systemLabel: '跟随系统',
  sourceLocale: 'zh_CN',
  fallbackLocale: 'zh_CN',
  sourceText: i18nSourceText,
  langs: [
    I18nLangDef(
      locale: 'zh_CN',
      label: '简体中文',
      map: zhCN,
    ),
    I18nLangDef(
      locale: 'en_US',
      label: 'English',
      map: enUS,
    ),
    I18nLangDef(
      locale: 'ja_JP',
      label: '日本語',
      map: jaJP,
    ),
  ],
);
